### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by mathew2214** [JoeJoeTV/AstroTuxLauncher#7]
Debian 12. 
it always just exits with [DedicatedServer/ERROR] Server was forcefully closed before registration
attached is the log file generated. 
no indication as to what actually caused the server to forcefully close. 

[astrotux_2024-06-25.log](https://github.com/user-attachments/files/15974399/astrotux_2024-06-25.log)

**Comment by JoeJoeTV** [comment]
You entered a domain for the PublicIP field, which is not supported by the Astroneer Dedicated Server software itself. Only IPv4 addresses (thus the name) that are not in the private range are allowed.
Since you disabled the network check, it will not tell you anything related to that.

**Comment by mathew2214** [comment]
so, DNS just isnt allowed? 
my ISP rotates my IP quite frequently, so it'd be fantastic if i could just have my clients use my domain name and let Dynamic DNS deal with my ISP's rotation nonsense automatically.

**Comment by mathew2214** [comment]
i see now. Astroneer's official blobs just dont have DNS support, which is why this application is failing when i try to simply use my domain.  
guess ill have to find some other way to deal with my ISP's rotation nonsense.
