### ISSUE TITLE
About rcon  

### ISSUE THREAD

**Issue by jiajiu123** [JoeJoeTV/AstroTuxLauncher#8]
I want to use rcon to operate the server, please open it.

**Comment by JoeJoeTV** [comment]
@jiajiu123 Are you talking about RCON in the manner that is used by Minecraft or Valve Game Servers?
Do you just want to be able to remotely send commands to the server?

The Astroneer Dedicated Server Software has a "console" TCP port where you can send it something and maybe get a response. That is what many talk about when they mean "RCON" for Astroneer.
This console port functionality is very broken though and not fun to be used directly as it only supports some commands where only some of them respond with a message at all and the messages are not really readable. Many commands also don't work at all and some may crash the server.
It's also not really safe to be opened up to the internet, as it is not encrypted and although there is a password that can be set, it is sent in plain text and not hashed.

This port is what AstroTuxLauncher mostly uses locally for it's console what I tried to make usable by humans.
But if you expose that publically, you are very vulnerable, if someone gets the password or sees it using mitm.

So the question is, do you just want to remotely control the server or what do you want to achieve?

**Comment by jiajiu123** [comment]
> @jiajiu123 Are you talking about RCON in the manner that is used by Minecraft or Valve Game Servers? Do you just want to be able to remotely send commands to the server?
> 
> The Astroneer Dedicated Server Software has a "console" TCP port where you can send it something and maybe get a response. That is what many talk about when they mean "RCON" for Astroneer. This console port functionality is very broken though and not fun to be used directly as it only supports some commands where only some of them respond with a message at all and the messages are not really readable. Many commands also don't work at all and some may crash the server. It's also not really safe to be opened up to the internet, as it is not encrypted and although there is a password that can be set, it is sent in plain text and not hashed.
> 
> This port is what AstroTuxLauncher mostly uses locally for it's console what I tried to make usable by humans. But if you expose that publically, you are very vulnerable, if someone gets the password or sees it using mitm.
> 
> So the question is, do you just want to remotely control the server or what do you want to achieve?

Yes,I need to remotely control the server.Because i have a dynamic public ip, I have written a program to automatically send the IP address when it changes, but I cannot find a method to automatically save and restart the server.(I used AI translation, please understand if there are any mistakes.)

**Comment by JoeJoeTV** [comment]
Currently, you can't set the IP address using the AstroTuxLauncher console or restart the server without stopping it and restarting AstroTuxLauncher, but these are features that I am looking at for the future.
The Astroneer Dedicated Server console port also doesn't allow you to change the IP.
So currently, your best bet would probably to have a separate script or program that gets the new IP, stops the server (You can send AstroTuxLauncher the SIGINT signal, same as pressing Ctrl+C in the console, this shuts the server down normally), replaces the IP in the `AstroServerSettings.ini` file and then starts AstroTuxLauncher again.

**Comment by JoeJoeTV** [comment]
@jiajiu123 But, if you just want AstroTuxLauncher to get the current public IP of the PC running the Server using a website like "whatismyip" or similar, then you're in luck, as that is already supported and will bechecked, when the server is started (Just make sure you set `OverwritePublicIP` to `true` in the `launcher.toml` file so that this is always done.

**Comment by jiajiu123** [comment]
I am running AstroTuxLauncher in Docker. If I use docker stop, will it cause the game save data to be lost?



---Original---
From: "Johannes ***@***.***&gt;
Date: Sun, Sep 15, 2024 00:53 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [JoeJoeTV/AstroTuxLauncher] About rcon   (Issue #8)




 
Currently, you can't set the IP address using the AstroTuxLauncher console or restart the server without stopping it and re-starting AstroTuxLauncher itself, but these are features that I am looking at for the future.
 The Astroneer Dedicated Server console port also doesn't allow you to change the IP.
 So currently, your best bet would probably to have a separate script or program that gets the new IP, stops the server (You can send AstroTuxLauncher the SIGINT signal, same as pressing Ctrl+C in the console, this shuts the server down normally), replaces the IP in the AstroServerSettings.ini file and then starts AstroTuxLauncher again.

**Comment by JoeJoeTV** [comment]
I don't know what docker stop actually does to stop the server. If it just kills all processes, then no. Again, you want to send a SIGNINT signal to AstroTuxLauncher and it will handle it for you.

**Comment by jiajiu123** [comment]
> I don't know what docker stop actually does to stop the server. If it just kills all processes, then no. Again, you want to send a SIGNINT signal to AstroTuxLauncher and it will handle it for you.

I understand,thank you.
